services:
  prolearning.api:
    image: prolearning.api
    ports:
      - "5075:8080"
    build:
      context: ProLearning.Api
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      ConnectionStrings__Database: "Host=database;Port=5432;Database=default_database;Username=postgres;Password=postgres;Include Error Detail=true"
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_database
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
