// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProLearning.Api.Database;

#nullable disable

namespace ProLearning.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412223559_AddSkillLevelToInterestAreaScoreBoost")]
    partial class AddSkillLevelToInterestAreaScoreBoost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducationLevelLearningActivity", b =>
                {
                    b.Property<int>("EducationLevelsId")
                        .HasColumnType("integer");

                    b.Property<int>("LearningActivitiesId")
                        .HasColumnType("integer");

                    b.HasKey("EducationLevelsId", "LearningActivitiesId");

                    b.HasIndex("LearningActivitiesId");

                    b.ToTable("EducationLevelLearningActivity");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.ToTable("EducationLevels");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.InterestArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.ToTable("InterestAreas");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.LearningActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LearningActivities");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.Recommendation.GoalScoreBoost", b =>
                {
                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<int>("LearningActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("GoalId", "LearningActivityId");

                    b.HasIndex("LearningActivityId");

                    b.ToTable("GoalScoreBoost");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.Recommendation.InterestAreaScoreBoost", b =>
                {
                    b.Property<int>("InterestAreaId")
                        .HasColumnType("integer");

                    b.Property<int>("LearningActivityId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("integer");

                    b.HasKey("InterestAreaId", "LearningActivityId");

                    b.HasIndex("LearningActivityId");

                    b.ToTable("InterestAreaScoreBoost");
                });

            modelBuilder.Entity("EducationLevelLearningActivity", b =>
                {
                    b.HasOne("ProLearning.Api.Domain.EducationLevel", null)
                        .WithMany()
                        .HasForeignKey("EducationLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLearning.Api.Domain.LearningActivity", null)
                        .WithMany()
                        .HasForeignKey("LearningActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProLearning.Api.Domain.Recommendation.GoalScoreBoost", b =>
                {
                    b.HasOne("ProLearning.Api.Domain.Goal", "Goal")
                        .WithMany("GoalScoreBoosts")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLearning.Api.Domain.LearningActivity", "LearningActivity")
                        .WithMany("GoalScoreBoosts")
                        .HasForeignKey("LearningActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("LearningActivity");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.Recommendation.InterestAreaScoreBoost", b =>
                {
                    b.HasOne("ProLearning.Api.Domain.InterestArea", "InterestArea")
                        .WithMany("InterestAreaScoreBoosts")
                        .HasForeignKey("InterestAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLearning.Api.Domain.LearningActivity", "LearningActivity")
                        .WithMany("InterestAreaScoreBoosts")
                        .HasForeignKey("LearningActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterestArea");

                    b.Navigation("LearningActivity");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.Goal", b =>
                {
                    b.Navigation("GoalScoreBoosts");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.InterestArea", b =>
                {
                    b.Navigation("InterestAreaScoreBoosts");
                });

            modelBuilder.Entity("ProLearning.Api.Domain.LearningActivity", b =>
                {
                    b.Navigation("GoalScoreBoosts");

                    b.Navigation("InterestAreaScoreBoosts");
                });
#pragma warning restore 612, 618
        }
    }
}
